### PR TITLE
Delete incorrectly labeled directory

### PR DESCRIPTION
**Pull request by ulya-tkch**
#18 cont

### CODE REVIEW

**Review by elisno — APPROVED** [review]
We'll need both directories available until cleanlab/cleanlab#435 is merged.
This can be merged right afterwards.

**Review by jwmueller — APPROVED** [review]
approving, but please think about whether "cifar10_outlier_detection" is really a better name than "outlier_detection_cifar10". I named it the latter in my edits because I think that is a more informative name.

**Comment by cgnorthcutt** [comment]
its subtle, but i agree with jonas bc tons of stuff has already been done on cifar-10, and the real value here is that it's outlier detection which has been done less on cifar-10.

(`out_of_distribution_detection_cifar10` could work too... a lot longer tho)

**Comment by huiwengoh** [comment]
Closing as issue is addressed in new PR: https://github.com/cleanlab/examples/pull/21

**Pull request closed without merging**
