### PR TITLE
Updated example notebook with integration examples

### PR DESCRIPTION
**Pull request by sanjanag**

### CODE REVIEW

**Review by jwmueller — APPROVED** [review]
LGTM overall, but I saw this warning in the final cell that I'm not sure is supposed to be visible (ideally can be quashed if easy to do)

Screen Shot 2023-07-18 at 12 49 30 AM

Also don't forget to verify these outputs remain unchanged after finalizing the cleanvision integration in datalab and merging the updated datalab code!

**Comment by sanjanag** [comment]
The warning is intentional because previously computed values are re-used, I can add a line which clears this. Sure, I'll run it again after the cleanlab code is merged.

**Comment by elisno** [comment]
I didn't expect the number of label errors to change in this notebook.

image

https://github.com/cleanlab/examples/assets/18127060/876e5502-ae5a-4a31-9357-ec0c9d1d0fe4

---

But the cleanvision results LGTM!

**Comment by sanjanag** [comment]
Good catch @elisno ! Ran the notebook again on fresh data, results look identical now.

**Review by elisno — APPROVED** [review]
Great work @sanjanag!

We can look at adding examples with more convincing issues found by cleanvision in a separate PR, if that's the goal.

**Pull request merged**
